connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbTest.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbWriter.java

fix(#148910) Mongos does not have a shard key and an error occurs when inserting it.

Fix mongo #148910

---

connectors-common/connector-core/pom.xml
connectors-common/connector-core/src/main/java/io/tapdata/base/ConnectorBase.java
connectors-common/connector-core/src/main/java/io/tapdata/exception/DatetimeFormatException.java
connectors-common/connector-core/src/test/java/io/tapdata/base/ConnectorBaseTest.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/config/MysqlConfig.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/writer/MysqlJdbcWriter.java
connectors-common/postgres-core/src/main/java/io/tapdata/connector/postgres/config/PostgresConfig.java
connectors-common/sql-core/src/main/java/io/tapdata/common/CommonDbConfig.java
connectors/elasticsearch-connector/src/main/java/io/tapdata/connector/elasticsearch/ElasticsearchConfig.java
connectors/elasticsearch-connector/src/main/java/io/tapdata/connector/elasticsearch/ElasticsearchConnector.java
connectors/elasticsearch-connector/src/main/java/io/tapdata/connector/elasticsearch/ElasticsearchRecordWriter.java
connectors/elasticsearch-connector/src/main/resources/spec_elasticsearch.json
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbTest.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/reader/MongodbV4StreamReader.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/reader/v3/MongodbV3StreamReader.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbMergeOperate.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbWriter.java
connectors/postgres-connector/src/main/resources/spec_postgres.json
connectors/postgres-connector/src/main/test/Main4.java
pom.xml

Reverts tapdata/tapdata-connectors#28

Revert "Feat mongo shard main" 28

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbConnector.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbUtil.java

fix(mongo): init default value into node config when init mongo  and node config is null or empty

---

connectors-javascript/zoho-crm-connector/src/main/javascript/io/tapdata/zoho/util/tap_util.js

print zoho-crm interface error.

fix: print zoho-crm interface error.

---

connectors/dummy-connector/pom.xml
connectors/dummy-connector/src/main/java/io/tapdata/dummy/utils/TapEventBuilder.java
connectors/dummy-connector/src/test/java/io/tapdata/dummy/utils/TapEventBuilderTest.java
connectors/pom.xml
connectors/tdengine-connector/pom.xml
connectors/tdengine-connector/src/main/java/io/tapdata/connector/tdengine/TDengineSuperRecordWriter.java
connectors/tdengine-connector/src/test/java/io/tapdata/connector/tdengine/TDengineSuperRecordWriterTest.java

Closes #150607
https://tapdata.coding.net/p/tapdata/bug-tracking/issues/150607/detail

perf(dummy): Optimize sync performance

---

connectors-common/kafka-core/pom.xml
connectors-common/kafka-core/src/main/java/io/tapdata/connector/kafka/KafkaService.java
connectors-common/kafka-core/src/test/java/io/tapdata/connector/kafka/KafkaServiceTest.java

fix: fix for kafka custom message body when obtain new Date()

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/ExecuteObject.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbConnector.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbExecuteCommandFunction.java

1. Fix filter and pipeline map null value issue
2. Fix cannot load empty collection's schema

Sam/fix v1.3.2 css

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbConnector.java

(cherry picked from commit 422c675016086dece78f33606a196c763a33d76e)

fix(mongodb): Cannot load empty table's schema

---

connectors-common/kafka-core/src/main/java/io/tapdata/connector/kafka/KafkaSRService.java
connectors-common/kafka-core/src/main/java/io/tapdata/connector/kafka/KafkaService.java
connectors-common/kafka-core/src/main/java/io/tapdata/connector/kafka/config/SchemaConfiguration.java

fix: kafka

---

connectors/mysql-connector/src/main/java/io/tapdata/connector/mysql/MysqlConnector.java
connectors/mysql-connector/src/main/resources/mysql-spec.json

remove mysql sync index process when create table

feat: Index Sync - Engine Closes TAP-1490

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/reader/v3/MongodbV3StreamReader.java

fix(Mongodb): When mongodb v3 do stream read, may cause a large delay

---

connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/MysqlConnectionTest.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/MysqlExceptionCollector.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/MysqlJdbcContextV2.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/MysqlReader.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/config/MysqlConfig.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/constant/DeployModeEnum.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/dml/MysqlRecordWriter.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/util/MysqlUtil.java
connectors-common/mysql-core/src/main/java/io/tapdata/connector/mysql/writer/MysqlSqlBatchWriter.java
connectors/mysql-connector/src/main/java/io/tapdata/connector/mysql/MysqlConnector.java
connectors/mysql-connector/src/main/resources/mysql-spec.json

feat: feat for mysql master slave architecture

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbMergeOperate.java
connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/writer/MongodbMergeOperateTest.java

fix(mongodb): 2024-05-16校验：MDM_catalogItem_taptest字段pricingType没有更新

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbMergeOperate.java
connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/writer/MongodbMergeOperateTest.java

TAP-2934 fix(mongodb): Master-slave have duplicate update

---

connectors/mysql-connector/src/main/java/io/tapdata/connector/mysql/MysqlConnector.java

(cherry picked from commit c4c0c7c3e3f02e5de75854ede6758e034e476251)

fix: mysql batchRead with streamingRead

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbConnector.java
connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/MongodbConnectorTest.java

TAP-3401 fix(MongoDB): MongoDB index exists error

---

connectors/mysql-connector/src/main/java/io/tapdata/connector/mysql/MysqlConnector.java

change mysql hash read sql, make it faster

fix: mysql hash read performance

---

connectors/mongodb-connector/pom.xml
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbMergeOperate.java
connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbWriter.java
connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/writer/MongodbMergeOperateTest.java

fix(mongodb): TAP-4207 Insert event support unset fields

---

connectors/elasticsearch-connector/src/main/java/io/tapdata/connector/elasticsearch/ElasticsearchConnector.java
connectors/elasticsearch-connector/src/main/java/io/tapdata/connector/elasticsearch/ElasticsearchRecordWriter.java

fix(elasticsearch): TAP-4526 Added write and update policy support

---

connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/writer/MongodbWriterTest.java

This reverts commit 8a4bffbbceff58396c81bca4b8d0c48af3faa93f.

Revert "fix: mongo unit test"

---

connectors/elasticsearch-connector/src/main/resources/spec_elasticsearch.json

Closes TAP-4710
还需合并到main分支，麻烦操作一下🙏

feat(elasticsearch): TAP-4710 Supports selective write update strategy

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/writer/MongodbWriter.java
connectors/mongodb-connector/src/test/java/io/tapdata/mongodb/writer/MongodbWriterTest.java

fix(mongodb): Unset cannot be handled correctly during normal writing

---

connectors-common/debezium-bucket/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnection.java
connectors-common/debezium-bucket/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
connectors-common/debezium-bucket/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlTaskContext.java
connectors-common/debezium-bucket/debezium-core/src/main/java/io/debezium/relational/RelationalDatabaseSchema.java
connectors-common/debezium-bucket/debezium-core/src/main/java/io/debezium/relational/TableId.java

mysql windows lower_case_table_names=2 database name should transfer to lowercase and not change table name

fix: TAP-5166

---

connectors/kafka-enhanced-connector/pom.xml
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/connector/error/KafkaErrorCodes.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/AbsSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/KafkaConfig.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/constants/KafkaSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/constants/ProducerRecordWrapper.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/schema_mode/CanalSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/schema_mode/DebeziumSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/schema_mode/FlinkSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/schema_mode/OriginalSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/schema_mode/StandardSchemaMode.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/service/KafkaService.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/utils/KafkaUtils.java
connectors/kafka-enhanced-connector/src/main/java/io/tapdata/kafka/utils/RecordHeadersUtils.java
connectors/kafka-enhanced-connector/src/main/resources/spec_kafka_enhanced.json

feat: TAP-6051 DB - Kafka Transformer

---

connectors/mongodb-connector/src/main/java/io/tapdata/mongodb/MongodbConnector.java
connectors/mongodb-lower-connector/src/main/java/io/tapdata/mongodb/MongodbLowerConnector.java

(cherry picked from commit 4ce0c1201ca0d3cf5c95508326eb6c7d0a72f171)

perf: Optimize mongodb index creation logic
